version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: Kredecki
      POSTGRES_PASSWORD: Inspekta1029!
      POSTGRES_DB: Inspekta
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    name: postgres_data
